#all: entropy defaultRand linearRandPeriod
all: defaultRand linearRandPeriod
#entropy : entropy.c
#	gcc entropy.c -o entropy

defaultRand: defaultRand.c
	gcc defaultRand.c -o defaultRand

linearRandPeriod: linearRandPeriod.c
	gcc linearRandPeriod.c -o linearRandPeriod
