/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arc4PRNG */

#ifndef _Included_arc4PRNG
#define _Included_arc4PRNG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arc4PRNG
 * Method:    runarc4
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc4PRNG_runarc4
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
