/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arc4JNI */

#ifndef _Included_arc4JNI
#define _Included_arc4JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arc4JNI
 * Method:    Setup
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_arc4JNI_Setup
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     arc4JNI
 * Method:    PRNG
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_arc4JNI_PRNG
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
